from sqlalchemy import Column, Integer, String, Date, Text, DateTime, Numeric, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()

# สร้าง Base class สำหรับ declarative models
class PurchaseOrder(Base):
    __tablename__ = 'po'

    # คอลัมน์หลักและข้อมูลทั่วไปของ PO
    po_id = Column(Integer, primary_key=True, autoincrement=True, comment='รหัส PO')
    po_poid = Column(Integer, comment='รหัส PO')
    po_pono = Column(String(100), comment='เลขที่ PO')
    po_podate = Column(Date, comment='วันที่ PO')
    po_project = Column(String(30), comment='รหัสโครงการ')
    po_system = Column(String(10), comment='รหัสระบบ')
    po_department = Column(String(10), comment='รหัสแผนก')
    po_memid = Column(String(10), comment='รหัสพนักงาน')
    po_prname = Column(String(100), comment='ชื่อ PR')
    po_trem = Column(String(100), comment='รหัสที่ส่งมอบ')
    po_contact = Column(String(300), server_default='', comment='ชื่อผู้ติดต่อ')
    po_prno = Column(String(30), comment='เลขที่ PR')
    po_contactno = Column(String(100), comment='เบอร์โทรผู้ติดต่อ')
    po_quono = Column(String(30), comment='เลขที่คำขอซื้อ')
    po_deliverydate = Column(Date, comment='วันที่ส่งมอบ')
    po_place = Column(String(300), comment='สถานที่ส่งมอบ')
    po_remark = Column(Text, comment='หมายเหตุ')
    po_status = Column(String(30), server_default='enable', comment='สถานะ PO')
    po_venderid = Column(Integer, comment='รหัสผู้จำหน่าย')
    po_vender = Column(String(100), comment='ชื่อผู้จำหน่าย') 
    po_open = Column(String(45), server_default='no', comment='สถานะเปิด')
    po_approve = Column(String(45), server_default='wait', comment='สถานะอนุมัติ')
    po_disapprove = Column(Text, comment='หมายเหตุอนุมัติ')
    po_qty = Column(Integer, comment='จำนวน')
    ic_status = Column(String(5), server_default='wait', comment='สถานะ IC')
    apv_open = Column(String(10), server_default='no', comment='สถานะอนุมัติเปิด')
    compcode = Column(String(45), comment='รหัสบริษัท')    
    useradd = Column(String(45), comment='ผู้เพิ่ม')
    usercreate = Column(DateTime, comment='วันที่เพิ่ม')
    useredit = Column(String(45), comment='ผู้แก้ไข')
    editdate = Column(DateTime, comment='วันที่แก้ไข')
    userdelete = Column(String(45), comment='ผู้ลบ')
    deletedate = Column(DateTime, comment='วันที่ลบ')
    po_vat = Column(Numeric(10,4), comment='VAT')
    po_vatper = Column(Integer, comment='เปอร์เซ็นต์ VAT')
    discounts1 = Column(String(50), comment='ส่วนลด 1')
    discounts2 = Column(String(50), comment='ส่วนลด 2')
    reject_remark = Column(String(300), comment='หมายเหตุอนุมัติ')
    reject_user = Column(String(300), comment='ผู้อนุมัติ')
    dis_remark = Column(String(255), comment='หมายเหตุอนุมัติ')
    dis_user = Column(String(255), comment='ผู้อนุมัติ')
    downper = Column(Numeric(12,2), comment='ส่วนลด')
    down = Column(Numeric(12,2), comment='ส่วนลด')
    sumdown = Column(Numeric(12,2), comment='ส่วนลดรวม')
    retentionper = Column(Numeric(12,2), comment='รักษาราคา')
    retention = Column(Numeric(12,2), comment='รักษาราคา')
    sumretention = Column(Numeric(12,2), comment='รักษาราคารวม')
    status_down = Column(String(255), comment='สถานะส่วนลด')
    status_retention = Column(String(255), comment='สถานะรักษาราคา')
    wo_ref = Column(String(255), comment='อ้างอิง WO')
    poi_deduct_status = Column(String(50), comment='สถานะการหัก')
    is_decrement = Column(String(10), server_default='no', comment='ลดลง')
    contact_store = Column(String(40), comment='ผู้ติดต่อคลัง')
    teamother = Column(String(255), comment='ทีมอื่น')

    # ความสัมพันธ์กับตาราง PurchaseOrderItem
    items = relationship("PurchaseOrderItem", back_populates="purchase_order")

# โมเดลสำหรับตาราง Purchase Order Item
class PurchaseOrderItem(Base):
    __tablename__ = 'po_item'

    # ข้อมูลหลักของรายการ
    poi_id = Column(Integer, primary_key=True, autoincrement=True, comment='รหัสรายการ PO')
    poi_matname = Column(String(300), server_default='', comment='ชื่อวัสดุ')
    poi_matcode = Column(String(100), comment='รหัสวัสดุ')
    poi_ref = Column(String(100), comment='เลขที่อ้างอิง')
    poi_costname = Column(String(300), comment='ชื่อต้นทุน')
    poi_costcode = Column(String(100), comment='รหัสต้นทุน')
    poi_qty = Column(Numeric(65,2), comment='จำนวน')
    poi_qtyic = Column(String(100), comment='จำนวน IC')
    poi_totqtyic = Column(String(100), comment='จำนวนรวม IC')
    poi_unitic = Column(String(255), comment='หน่วย IC')
    poi_unit = Column(String(100), comment='หน่วย')
    poi_priceunit = Column(Numeric(65,2), comment='ราคาต่อหน่วย')
    poi_amount = Column(Numeric(65,2), comment='จำนวนเงิน')
    poi_discountper1 = Column(Numeric(65,2), comment='เปอร์เซ็นต์ส่วนลด 1')
    poi_discountper2 = Column(Numeric(65,2), comment='เปอร์เซ็นต์ส่วนลด 2')
    poi_disamt = Column(Numeric(65,2), comment='จำนวนเงินส่วนลด')
    poi_vat = Column(Numeric(65,2), comment='VAT')
    poi_vatper = Column(Integer, nullable=False, comment='เปอร์เซ็นต์ VAT')
    poi_remark = Column(String(300), server_default='', comment='หมายเหตุ')
    poi_netamt = Column(Numeric(15,4), comment='จำนวนเงินสุทธิ')
    poi_receive = Column(Integer, server_default='0', comment='จำนวนที่รับ')
    poi_receivetot = Column(Integer, server_default='0', comment='จำนวนที่รับรวม')
    po_disex = Column(Numeric(100,2), server_default='0.00', comment='ส่วนลดพิเศษ')
    poi_item = Column(Integer, comment='ลำดับรายการ')
    ic_receive = Column(Integer, server_default='0', comment='จำนวนรับ IC')
    compcode = Column(String(100), comment='รหัสบริษัท')
    pri_id = Column(Integer, comment='รหัส PR Item')
    poi_chk = Column(String(100), comment='สถานะตรวจสอบ')
    poi_discountper3 = Column(Numeric(65,2), comment='เปอร์เซ็นต์ส่วนลด 3')
    poi_discountper4 = Column(Numeric(65,2), comment='เปอร์เซ็นต์ส่วนลด 4')
    poi_disce = Column(Numeric(65,2), comment='ส่วนลดพิเศษ')
    po_asset = Column(String(100), comment='ทรัพย์สิน')
    po_assetid = Column(String(100), comment='รหัสทรัพย์สิน')
    po_assetname = Column(String(100), comment='ชื่อทรัพย์สิน')
    pr_no = Column(String(100), comment='เลขที่ PR')
    po_boq = Column(String(200), comment='BOQ')
    cost_type = Column(String(100), comment='ประเภทต้นทุน')
    remark_mat = Column(String(100), comment='หมายเหตุวัสดุ')
    type_cost = Column(String(100), comment='ประเภทต้นทุน')
    datesend = Column(String(100), comment='วันที่ส่ง')
    wo_ref = Column(String(255), comment='อ้างอิง WO')
    poi_deduct_status = Column(String(50), comment='สถานะการหัก')
    poi_sumdeduct = Column(Numeric(65,2), comment='ยอดรวมหัก')
    poi_project = Column(String(10), comment='รหัสโครงการ')
    poid = Column(Integer, ForeignKey('po.po_id'), comment='รหัส PO')

    # Foreign Key และ Relationship
    purchase_order = relationship("PurchaseOrder", back_populates="items", foreign_keys=[poid])
