from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Project(Base):
    __tablename__ = 'project'

    project_id = Column(Integer, primary_key=True, autoincrement=True)
    project_code = Column(String(100))
    project_pono = Column(String(20))
    project_name = Column(String(100))
    project_worktype = Column(String(10))
    project_type = Column(String(10))
    project_address = Column(String)
    project_cname = Column(String(100))
    project_tel = Column(String(30))
    project_fax = Column(String(30))
    project_email = Column(String(100))
    project_biztype = Column(String(10))
    project_mcode = Column(String(100))
    project_mnameth = Column(String(100), server_default='')
    project_mnameen = Column(String(100))
    project_maddress = Column(String(255))
    project_onertel = Column(String(30))
    project_owneremail = Column(String(100))
    project_mfax = Column(String(30))
    project_bnameth = Column(String(100))
    project_bnameen = Column(String(100))
    project_wt = Column(Integer)
    project_vat = Column(Integer)
    project_budget = Column(Integer)
    project_boq = Column(String(2))
    project_advance_1 = Column(Integer)
    project_advance_2 = Column(Integer)
    project_lessadvance = Column(Integer)
    project_lessadvance_2 = Column(Integer)
    project_lessretention = Column(Integer)
    project_lessretention_2 = Column(Integer)
    project_lessretentionmethod = Column(String(20))
    project_baddress = Column(String)
    project_btel = Column(String(30))
    project_bfax = Column(String(30))
    project_detail = Column(String)
    project_value = Column(String)
    project_contract = Column(String(100))
    project_start = Column(String)
    project_stop = Column(String)
    project_engineer = Column(String(100))
    project_create = Column(String)
    project_update = Column(String)
    project_status = Column(String(10), server_default='0')
    project_user = Column(String(100))
    compcode = Column(String(45))
    project_mtel = Column(String(200))
    project_img = Column(String(200))
    edituser = Column(String(100))
    editdate = Column(String)
    bd_tenid = Column(String(255))
    bd_tenname = Column(String(255))
    chkconbqq = Column(Integer, server_default='0')
    controlbg = Column(Integer, server_default='0')
    forcast_useredit = Column(String(200))
    revise = Column(String(200), server_default='0')
    revise_user = Column(String(200))
    approve_bg = Column(String(200))
    approve_user = Column(String(200))
    project_sub = Column(String(50))
    project_substatus = Column(String(50))
    project_approvecontrol = Column(String(50), server_default='0')
    c_pr = Column(String(5), server_default='0')
    c_po = Column(String(5), server_default='0')
    c_wo = Column(String(5), server_default='0')
    c_pt = Column(String(5), server_default='0')
    a_pr = Column(String(5), server_default='0')
    a_po = Column(String(5), server_default='0')
    a_wo = Column(String(5), server_default='0')
    a_pt = Column(String(5), server_default='0')
    acc_primary = Column(String(10))
    acc_secondary = Column(String(10))
    c_bk = Column(String(5), server_default='0')
    store_center = Column(String(100))
    c_ap = Column(String(5), server_default='0')
    c_ic = Column(String(5), server_default='0')
    gl_for_ic = Column(Integer)
    project_department = Column(Integer)
    remark_admin = Column(String)
    remark_contact = Column(String)
    remark_consult = Column(String)
    remark_subpro = Column(String)
    c_td = Column(Integer, server_default='0')
    a_td = Column(Integer, server_default='1')
    business_unit = Column(String(10))