from sqlalchemy import Column, Integer, String, Date, Text, DateTime, Numeric, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()

class Pr(Base):
    __tablename__ = 'pr'

    # คอลัมน์หลักและข้อมูลทั่วไปของ PR
    pr_prid = Column(Integer, primary_key=True, autoincrement=True)
    pr_item = Column(String(11))
    pr_prno = Column(String(30), comment='เลขที่ PR')
    pr_prdate = Column(Date)
    pr_memid = Column(String(100))
    pr_reqname = Column(String(200))
    pr_project = Column(String(200))
    pr_system = Column(String(20))
    pr_costtype = Column(String(10))
    pr_department = Column(String(100))
    pr_vender = Column(String(200))
    pr_deliplace = Column(String(150))
    pr_delidate = Column(String(20))
    pr_status = Column(String(20), server_default='enable')
    pr_remark = Column(String(100))
    pr_approve = Column(String(100))
    pe_approve = Column(String(100))
    pm_approve = Column(String(100))
    director_approve = Column(String(100))
    approve_date = Column(Date)
    pr_disremark = Column(String(200))
    po_open = Column(String(45), server_default='no')
    po_count = Column(String(255))
    useradd = Column(String(100))
    usercreate = Column(DateTime)
    compcode = Column(String(45))
    purchase_type = Column(String(3))
    edituser = Column(String(100))
    editdate = Column(DateTime)
    deluser = Column(String(100))
    deldate = Column(DateTime)
    pono = Column(String(100))
    wo_open = Column(String(100))
    express = Column(String(10))
    reject_remark = Column(String(300))
    reject_user = Column(String(300))
    dis_remark = Column(String(255))
    dis_user = Column(String(255))
    pri_compare = Column(String(100))
    compare = Column(String(100))
    reject_date = Column(DateTime)
    subid = Column(String(255))
    subname = Column(String(255))
    wo = Column(String(255))
    is_decrement = Column(String(10), server_default='no')
    pr_postatus = Column(String(1))

    # ความสัมพันธ์กับตาราง PrItem
    items = relationship("PrItem", back_populates="pr")

class PrItem(Base):
    __tablename__ = 'pr_item'

    # คอลัมน์หลักและข้อมูลทั่วไปของ PR Item
    pri_id = Column(Integer, primary_key=True, autoincrement=True)
    pri_matname = Column(String(250))
    pri_matcode = Column(String(100))
    pri_ref = Column(String(30), nullable=False)
    pri_costcode = Column(String(30))
    pri_costname = Column(String(100))
    pri_qty = Column(Numeric(11,4))
    pri_unit = Column(String(30))
    pri_priceunit = Column(Numeric(11,4))
    pri_amount = Column(Numeric(11,4), server_default='0.0000')
    pri_discountper1 = Column(Numeric(11,4))
    pri_discountper2 = Column(Numeric(11,4))
    pri_disamt = Column(Numeric(11,4), server_default='0.0000')
    pri_vat = Column(Numeric(11,4))
    pri_remark = Column(String(500))
    pri_netamt = Column(Numeric(11,4))
    datesend = Column(String(30))
    pri_status = Column(String(255))
    pri_pono = Column(String(100))
    pri_count = Column(String(255))
    compcode = Column(String(45))
    pri_discountper3 = Column(Numeric(11,4), nullable=False)
    pri_discountper4 = Column(Numeric(11,4), nullable=False)
    pr_asset = Column(String(20))
    pr_assetid = Column(String(20))
    pr_assetname = Column(String(20))
    poi_qty = Column(Numeric(12,4))
    pri_cpqtyic = Column(String(255))
    pri_pqtyic = Column(String(255))
    pri_punitic = Column(String(255))
    pri_pdiscex = Column(Integer, server_default='0')
    pri_tovat = Column(String(255))
    pri_boqid = Column(String(255))
    pri_boqrow = Column(Integer)
    pri_sumqty = Column(String(100))
    cost_type = Column(String(100))
    remark_mat = Column(String(100))
    boq_type = Column(String(1))
    pri_unitcode = Column(String(10))
    pri_uniticcode = Column(String(10))
    pri_project = Column(String(10))
    prid = Column(Integer, ForeignKey('pr.pr_prid'))

    # ความสัมพันธ์กับตาราง Pr
    pr = relationship("Pr", back_populates="items")
